version: "3.1"

services:

  mysql_db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default

  python-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    networks:
      - default

networks:
  default:
    driver: bridge