version: "3.1"

services:

  mysql_db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    container_name: telegramBot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "cumcumcum"
    networks:
      - default

  python-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    container_name: telegramBot-python
    networks:
      - default

networks:
  default:
    driver: bridge